<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GuarantorsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('guarantors')->delete();
        
        \DB::table('guarantors')->insert(array (
            0 => 
            array (
                'id' => 1,
                'full_name' => 'guarantors one',
                'phone_number' => '08743322422',
                'email' => 'Kennith70@yahoo.com',
                'street' => '96339 Israel Cliff',
                'state' => '294',
                'lga' => 'zaria',
                'profile_picture' => 'uploads/driver/guarantor_images/1698672302bdFqhNfVIB.png',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 1,
                'loadable_type' => 'App\\Models\\Driver',
                'created_at' => '2023-10-30 13:25:02',
                'updated_at' => '2023-10-30 13:25:02',
            ),
            1 => 
            array (
                'id' => 2,
                'full_name' => 'Dawn Franecki',
                'phone_number' => '79933322232',
                'email' => 'Elenor65@yahoo.com',
                'street' => '562 Alex Harbor',
                'state' => '294',
                'lga' => 'liverpool',
                'profile_picture' => 'uploads/driver/guarantor_images/16986723024LTXjYa0NH.png',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 1,
                'loadable_type' => 'App\\Models\\Driver',
                'created_at' => '2023-10-30 13:25:02',
                'updated_at' => '2023-10-30 13:25:02',
            ),
            2 => 
            array (
                'id' => 3,
                'full_name' => 'guarantors one',
                'phone_number' => '07843322422',
                'email' => 'Keyshawn.Abbott@gmail.com',
                'street' => '521 Little Loop',
                'state' => '294',
                'lga' => 'zaria',
                'profile_picture' => 'uploads/driver/guarantor_images/1698672322aMNIBVsWT3.png',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 2,
                'loadable_type' => 'App\\Models\\Driver',
                'created_at' => '2023-10-30 13:25:22',
                'updated_at' => '2023-10-30 13:25:22',
            ),
            3 => 
            array (
                'id' => 4,
                'full_name' => 'Dave Abernathy',
                'phone_number' => '79933322232',
                'email' => 'Anabel.Donnelly73@gmail.com',
                'street' => '3680 Koch Road',
                'state' => '294',
                'lga' => 'liverpool',
                'profile_picture' => 'uploads/driver/guarantor_images/1698672322TyY0MXgK13.png',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 2,
                'loadable_type' => 'App\\Models\\Driver',
                'created_at' => '2023-10-30 13:25:22',
                'updated_at' => '2023-10-30 13:25:22',
            ),
            4 => 
            array (
                'id' => 5,
                'full_name' => 'guarantors one',
                'phone_number' => '07843322422',
                'email' => 'Jasen_Morissette98@yahoo.com',
                'street' => '87171 Macejkovic Trace',
                'state' => '294',
                'lga' => 'zaria',
                'profile_picture' => 'uploads/driver/guarantor_images/1698672329M54thbB9PB.png',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 3,
                'loadable_type' => 'App\\Models\\Driver',
                'created_at' => '2023-10-30 13:25:29',
                'updated_at' => '2023-10-30 13:25:29',
            ),
            5 => 
            array (
                'id' => 6,
                'full_name' => 'Ms. Andrea Hauck',
                'phone_number' => '79933322232',
                'email' => 'Rusty_Rice@gmail.com',
                'street' => '5357 Smitham Crossing',
                'state' => '294',
                'lga' => 'liverpool',
                'profile_picture' => 'uploads/driver/guarantor_images/1698672329BFxwXf00xd.png',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 3,
                'loadable_type' => 'App\\Models\\Driver',
                'created_at' => '2023-10-30 13:25:29',
                'updated_at' => '2023-10-30 13:25:29',
            ),
            6 => 
            array (
                'id' => 7,
                'full_name' => 'guarantors one',
                'phone_number' => '07843322422',
                'email' => 'Leonard.Lockman51@hotmail.com',
                'street' => '78150 Kassulke Neck',
                'state' => '294',
                'lga' => 'zaria',
                'profile_picture' => 'uploads/driver/guarantor_images/1698672342zost9UjLTI.png',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 4,
                'loadable_type' => 'App\\Models\\Driver',
                'created_at' => '2023-10-30 13:25:42',
                'updated_at' => '2023-10-30 13:25:42',
            ),
            7 => 
            array (
                'id' => 8,
                'full_name' => 'Bobby Ratke',
                'phone_number' => '79933322232',
                'email' => 'Marques_Harris86@hotmail.com',
                'street' => '27636 Feest Pines',
                'state' => '294',
                'lga' => 'liverpool',
                'profile_picture' => 'uploads/driver/guarantor_images/1698672342Vr1IBy10qa.png',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 4,
                'loadable_type' => 'App\\Models\\Driver',
                'created_at' => '2023-10-30 13:25:42',
                'updated_at' => '2023-10-30 13:25:42',
            ),
            8 => 
            array (
                'id' => 9,
                'full_name' => 'guarantors one',
                'phone_number' => '07843322422',
                'email' => 'Ramon_Hickle54@gmail.com',
                'street' => '743 Zora Pine',
                'state' => '294',
                'lga' => 'zaria',
                'profile_picture' => 'uploads/driver/guarantor_images/1698672359kliHt3gSrv.png',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 5,
                'loadable_type' => 'App\\Models\\Driver',
                'created_at' => '2023-10-30 13:25:59',
                'updated_at' => '2023-10-30 13:25:59',
            ),
            9 => 
            array (
                'id' => 10,
                'full_name' => 'Alison Bayer',
                'phone_number' => '79933322232',
                'email' => 'Malinda_Graham82@hotmail.com',
                'street' => '54233 Wilkinson Cape',
                'state' => '294',
                'lga' => 'liverpool',
                'profile_picture' => 'uploads/driver/guarantor_images/1698672359CnhC9EX45D.png',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 5,
                'loadable_type' => 'App\\Models\\Driver',
                'created_at' => '2023-10-30 13:25:59',
                'updated_at' => '2023-10-30 13:25:59',
            ),
            10 => 
            array (
                'id' => 11,
                'full_name' => 'guarantors one',
                'phone_number' => '08743322420',
                'email' => 'Viva42@hotmail.com',
                'street' => '996 Billie Avenue',
                'state' => '294',
                'lga' => '3',
                'profile_picture' => 'uploads/agent/guarantor_images/16986725476uOQQWQVk0.png',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 1,
                'loadable_type' => 'App\\Models\\ShippingCompany',
                'created_at' => '2023-10-30 13:29:07',
                'updated_at' => '2023-10-30 13:29:07',
            ),
            11 => 
            array (
                'id' => 12,
                'full_name' => 'guarantors one',
                'phone_number' => '08743322420',
                'email' => 'Jerrold93@gmail.com',
                'street' => '36848 Pacocha Estate',
                'state' => '294',
                'lga' => '3',
                'profile_picture' => 'uploads/agent/guarantor_images/1698672561FcktdhYfgi.png',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 2,
                'loadable_type' => 'App\\Models\\ShippingCompany',
                'created_at' => '2023-10-30 13:29:21',
                'updated_at' => '2023-10-30 13:29:21',
            ),
            12 => 
            array (
                'id' => 13,
                'full_name' => 'guarantors one',
                'phone_number' => '08743322420',
                'email' => 'Jovan44@yahoo.com',
                'street' => '857 Reichert Drive',
                'state' => '294',
                'lga' => '3',
                'profile_picture' => 'uploads/agent/guarantor_images/1698672585LjzGnif6BA.png',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 3,
                'loadable_type' => 'App\\Models\\ShippingCompany',
                'created_at' => '2023-10-30 13:29:45',
                'updated_at' => '2023-10-30 13:29:45',
            ),
            13 => 
            array (
                'id' => 14,
                'full_name' => 'guarantors one',
                'phone_number' => '08743322422',
                'email' => 'Lessie_Russel54@example.net',
                'street' => '57127 Bogisich Village',
                'state' => '294',
                'lga' => '1',
                'profile_picture' => 'uploads/agent/guarantor_images/1698672987uYYDTCmJRv.png',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 1,
                'loadable_type' => 'App\\Models\\Agent',
                'created_at' => '2023-10-30 13:36:27',
                'updated_at' => '2023-10-30 13:36:27',
            ),
            14 => 
            array (
                'id' => 15,
                'full_name' => 'Edgar Koch',
                'phone_number' => '79933322232',
                'email' => 'Lew.Oberbrunner38@example.org',
                'street' => '36930 Langworth Station',
                'state' => '294',
                'lga' => '1',
                'profile_picture' => 'uploads/agent/guarantor_images/169867298735N9rOhHWl.png',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 1,
                'loadable_type' => 'App\\Models\\Agent',
                'created_at' => '2023-10-30 13:36:27',
                'updated_at' => '2023-10-30 13:36:27',
            ),
            15 => 
            array (
                'id' => 16,
                'full_name' => 'guarantors one',
                'phone_number' => '08743322422',
                'email' => 'Pat_Johnson@example.org',
                'street' => '30008 Roger Turnpike',
                'state' => '294',
                'lga' => '1',
                'profile_picture' => 'uploads/driver_manager/guarantor_images/1698673081y92MXiYl4E.jpg',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 1,
                'loadable_type' => 'App\\Models\\DriverManger',
                'created_at' => '2023-10-30 13:38:01',
                'updated_at' => '2023-10-30 13:38:01',
            ),
            16 => 
            array (
                'id' => 17,
                'full_name' => 'Marcos Runolfsdottir',
                'phone_number' => '79933322232',
                'email' => 'Odessa76@example.org',
                'street' => '827 Breitenberg Field',
                'state' => '294',
                'lga' => '1',
                'profile_picture' => 'uploads/driver_manager/guarantor_images/1698673081vSxoi8y76a.png',
                'state_of_residence' => NULL,
                'city_of_residence' => NULL,
                'loadable_id' => 1,
                'loadable_type' => 'App\\Models\\DriverManger',
                'created_at' => '2023-10-30 13:38:01',
                'updated_at' => '2023-10-30 13:38:01',
            ),
        ));
        
        
    }
}