<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LoadPackagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('load_packages')->delete();
        
        \DB::table('load_packages')->insert(array (
            0 => 
            array (
                'id' => '1',
                'uuid' => '1f818943-4c86-4e69-861e-8879f0a89bee',
                'user_id' => '3',
                'load_type_id' => '1',
                'load_type_name' => 'package',
                'deliver_from' => 'address',
                'to_office_id' => NULL,
                'sender_location' => 'Okpe Delta',
                'receiver_location' => 'Oguta Imo',
                'distance' => NULL,
                'sender_email' => 'ada@gmail.com',
                'sender_name' => 'Ada',
                'sender_phone' => '+23488393322',
                'sender_lga' => '199',
                'sender_street' => 'Okpe street',
                'sender_state' => '10',
                'sender_apartment' => '33',
                'sender_apartment_no' => '22',
                'deliver_to' => 'address',
                'from_office_id' => NULL,
                'receiver_name' => 'Ken',
                'receiver_email' => 'kkk@gmail.com',
                'receiver_phone' => '09088777343',
                'receiver_lga' => '309',
                'receiver_state' => '17',
                'receiver_street' => 'Oguta street',
                'receiver_apartment' => '88',
                'receiver_apartment_no' => '23',
                'is_document' => 'No',
                'document' => NULL,
                'description' => 'Generator',
                'weight' => '12.00',
                'width' => '66.00',
                'length' => '88.00',
                'height' => '50.00',
                'insure_it' => 'Yes',
                'insure_amount' => '300000.00',
                'delivery_fee' => '13700.00',
                'total_amount' => '313700.00',
                'is_fragile' => 'Yes',
                'created_at' => '2024-02-17 09:22:56',
                'updated_at' => '2024-02-17 09:22:56',
            ),
            1 => 
            array (
                'id' => '2',
                'uuid' => 'fe7fc55e-266d-474f-9bcf-f1c95c4b79d0',
                'user_id' => '3',
                'load_type_id' => '1',
                'load_type_name' => 'package',
                'deliver_from' => 'address',
                'to_office_id' => NULL,
                'sender_location' => 'Itu Akwa Ibom',
                'receiver_location' => 'Obowo Imo',
                'distance' => NULL,
                'sender_email' => 'jide@gmail.com',
                'sender_name' => 'Jide',
                'sender_phone' => '+23488393333',
                'sender_lga' => '54',
                'sender_street' => 'Itu street',
                'sender_state' => '3',
                'sender_apartment' => '22',
                'sender_apartment_no' => '22',
                'deliver_to' => 'address',
                'from_office_id' => NULL,
                'receiver_name' => 'Ken',
                'receiver_email' => 'kkk@gmail.com',
                'receiver_phone' => '09088227766',
                'receiver_lga' => '308',
                'receiver_state' => '17',
                'receiver_street' => 'Obowo street',
                'receiver_apartment' => '88',
                'receiver_apartment_no' => '23',
                'is_document' => 'Yes',
                'document' => NULL,
                'description' => 'Transcript',
                'weight' => '0.00',
                'width' => NULL,
                'length' => NULL,
                'height' => NULL,
                'insure_it' => 'No',
                'insure_amount' => NULL,
                'delivery_fee' => '7600.00',
                'total_amount' => '7600.00',
                'is_fragile' => 'No',
                'created_at' => '2024-02-17 10:40:27',
                'updated_at' => '2024-02-17 11:12:51',
            ),
            2 => 
            array (
                'id' => '3',
                'uuid' => '9bfbb183-e167-4f6e-adc1-1d6b53a900fb',
                'user_id' => '3',
                'load_type_id' => '1',
                'load_type_name' => 'package',
                'deliver_from' => 'address',
                'to_office_id' => NULL,
                'sender_location' => 'Fufure Adamawa',
                'receiver_location' => 'Isu Imo',
                'distance' => NULL,
                'sender_email' => 'tony@gmail.com',
                'sender_name' => 'Tony',
                'sender_phone' => '+23488393311',
                'sender_lga' => '19',
                'sender_street' => 'Fufure',
                'sender_state' => '2',
                'sender_apartment' => '4',
                'sender_apartment_no' => '90',
                'deliver_to' => 'address',
                'from_office_id' => NULL,
                'receiver_name' => 'Ken',
                'receiver_email' => 'kkk@gmail.com',
                'receiver_phone' => '09088227766',
                'receiver_lga' => '302',
                'receiver_state' => '17',
                'receiver_street' => 'Isu street',
                'receiver_apartment' => '88',
                'receiver_apartment_no' => '23',
                'is_document' => 'Yes',
                'document' => NULL,
                'description' => 'Certificate',
                'weight' => '0.00',
                'width' => NULL,
                'length' => NULL,
                'height' => NULL,
                'insure_it' => 'No',
                'insure_amount' => NULL,
                'delivery_fee' => '7300.00',
                'total_amount' => '7300.00',
                'is_fragile' => 'No',
                'created_at' => '2024-02-17 11:18:55',
                'updated_at' => '2024-02-17 11:18:55',
            ),
            3 => 
            array (
                'id' => '4',
                'uuid' => '8231bb42-36ab-44c2-a7af-abbde519d8bc',
                'user_id' => '3',
                'load_type_id' => '1',
                'load_type_name' => 'package',
                'deliver_from' => 'address',
                'to_office_id' => NULL,
                'sender_location' => 'Bende Abia',
                'receiver_location' => 'Kwami Gombe',
                'distance' => NULL,
                'sender_email' => 'david@gmail.com',
                'sender_name' => 'david',
                'sender_phone' => '+23488393399',
                'sender_lga' => '4',
                'sender_street' => 'Bende street',
                'sender_state' => '1',
                'sender_apartment' => '4',
                'sender_apartment_no' => '2',
                'deliver_to' => 'address',
                'from_office_id' => NULL,
                'receiver_name' => 'Kenny',
                'receiver_email' => 'kenny@gmail.com',
                'receiver_phone' => '09088777355',
                'receiver_lga' => '289',
                'receiver_state' => '16',
                'receiver_street' => 'Kwami street',
                'receiver_apartment' => '88',
                'receiver_apartment_no' => '23',
                'is_document' => 'No',
                'document' => NULL,
                'description' => 'Refrigerator',
                'weight' => '9.00',
                'width' => '66.00',
                'length' => '88.00',
                'height' => '50.00',
                'insure_it' => 'No',
                'insure_amount' => NULL,
                'delivery_fee' => '8600.00',
                'total_amount' => '8600.00',
                'is_fragile' => 'Yes',
                'created_at' => '2024-02-17 11:27:46',
                'updated_at' => '2024-02-17 11:27:46',
            ),
        ));
        
        
    }
}