<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LoadPackageTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('load_package')->delete();
        
        \DB::table('load_package')->insert(array (
            0 => 
            array (
                'id' => 1,
                'loadoard_id' => 1,
                'deliver_from' => 'address',
                'to_office_id' => 1,
                'sender_name' => 'NULL',
                'sender_phone' => 'NULL',
                'sender_zipcode' => 'NULL',
                'sender_city' => 'NULL',
                'sender_street' => 'NULL',
                'sender_number' => 'NULL',
                'sender_appartment' => 'NULL',
                'deliver_to' => 'address',
                'from_office_id' => 1,
                'receiver_name' => 'NULL',
                'receiver_phone' => 'NULL',
                'receiver_zipcode' => 'NULL',
                'receiver_city' => 'NULL',
                'receiver_street' => 'NULL',
                'receiver_number' => 'NULL',
                'receiver_appartment' => 'NULL',
                'is_document' => 'No',
                'description' => NULL,
                'weight' => '2.00',
                'width' => '2.00',
                'length' => '2.00',
                'height' => '2.00',
                'insure_it' => 'Yes',
                'insure_amount' => '0.00',
                'is_fragile' => 'Yes',
            ),
            1 => 
            array (
                'id' => 2,
                'loadoard_id' => 2,
                'deliver_from' => 'office',
                'to_office_id' => 1,
                'sender_name' => 'NULL',
                'sender_phone' => 'NULL',
                'sender_zipcode' => 'NULL',
                'sender_city' => 'NULL',
                'sender_street' => 'NULL',
                'sender_number' => 'NULL',
                'sender_appartment' => 'NULL',
                'deliver_to' => 'office',
                'from_office_id' => 1,
                'receiver_name' => 'NULL',
                'receiver_phone' => 'NULL',
                'receiver_zipcode' => 'NULL',
                'receiver_city' => 'NULL',
                'receiver_street' => 'NULL',
                'receiver_number' => 'NULL',
                'receiver_appartment' => 'NULL',
                'is_document' => 'Yes',
                'description' => NULL,
                'weight' => '2.00',
                'width' => '2.00',
                'length' => '2.00',
                'height' => '2.00',
                'insure_it' => 'Yes',
                'insure_amount' => '0.00',
                'is_fragile' => 'Yes',
            ),
            2 => 
            array (
                'id' => 3,
                'loadoard_id' => 3,
                'deliver_from' => 'address',
                'to_office_id' => 1,
                'sender_name' => 'NULL',
                'sender_phone' => 'NULL',
                'sender_zipcode' => 'NULL',
                'sender_city' => 'NULL',
                'sender_street' => 'NULL',
                'sender_number' => 'NULL',
                'sender_appartment' => 'NULL',
                'deliver_to' => 'address',
                'from_office_id' => 1,
                'receiver_name' => 'NULL',
                'receiver_phone' => 'NULL',
                'receiver_zipcode' => 'NULL',
                'receiver_city' => 'NULL',
                'receiver_street' => 'NULL',
                'receiver_number' => 'NULL',
                'receiver_appartment' => 'NULL',
                'is_document' => 'Yes',
                'description' => NULL,
                'weight' => '2.00',
                'width' => '2.00',
                'length' => '2.00',
                'height' => '2.00',
                'insure_it' => 'Yes',
                'insure_amount' => '0.00',
                'is_fragile' => 'Yes',
            ),
            3 => 
            array (
                'id' => 4,
                'loadoard_id' => 4,
                'deliver_from' => 'office',
                'to_office_id' => 1,
                'sender_name' => 'NULL',
                'sender_phone' => 'NULL',
                'sender_zipcode' => 'NULL',
                'sender_city' => 'NULL',
                'sender_street' => 'NULL',
                'sender_number' => 'NULL',
                'sender_appartment' => 'NULL',
                'deliver_to' => 'office',
                'from_office_id' => 1,
                'receiver_name' => 'NULL',
                'receiver_phone' => 'NULL',
                'receiver_zipcode' => 'NULL',
                'receiver_city' => 'NULL',
                'receiver_street' => 'NULL',
                'receiver_number' => 'NULL',
                'receiver_appartment' => 'NULL',
                'is_document' => 'No',
                'description' => NULL,
                'weight' => '2.00',
                'width' => '2.00',
                'length' => '2.00',
                'height' => '2.00',
                'insure_it' => 'Yes',
                'insure_amount' => '0.00',
                'is_fragile' => 'Yes',
            ),
            4 => 
            array (
                'id' => 5,
                'loadoard_id' => 5,
                'deliver_from' => 'address',
                'to_office_id' => 1,
                'sender_name' => 'NULL',
                'sender_phone' => 'NULL',
                'sender_zipcode' => 'NULL',
                'sender_city' => 'NULL',
                'sender_street' => 'NULL',
                'sender_number' => 'NULL',
                'sender_appartment' => 'NULL',
                'deliver_to' => 'office',
                'from_office_id' => 1,
                'receiver_name' => 'NULL',
                'receiver_phone' => 'NULL',
                'receiver_zipcode' => 'NULL',
                'receiver_city' => 'NULL',
                'receiver_street' => 'NULL',
                'receiver_number' => 'NULL',
                'receiver_appartment' => 'NULL',
                'is_document' => 'No',
                'description' => NULL,
                'weight' => '22.00',
                'width' => '2.00',
                'length' => '2.00',
                'height' => '2.00',
                'insure_it' => 'Yes',
                'insure_amount' => '0.00',
                'is_fragile' => 'Yes',
            ),
            5 => 
            array (
                'id' => 6,
                'loadoard_id' => 6,
                'deliver_from' => 'office',
                'to_office_id' => 1,
                'sender_name' => 'NULL',
                'sender_phone' => 'NULL',
                'sender_zipcode' => 'NULL',
                'sender_city' => 'NULL',
                'sender_street' => 'NULL',
                'sender_number' => 'NULL',
                'sender_appartment' => 'NULL',
                'deliver_to' => 'address',
                'from_office_id' => 1,
                'receiver_name' => 'NULL',
                'receiver_phone' => 'NULL',
                'receiver_zipcode' => 'NULL',
                'receiver_city' => 'NULL',
                'receiver_street' => 'NULL',
                'receiver_number' => 'NULL',
                'receiver_appartment' => 'NULL',
                'is_document' => 'No',
                'description' => NULL,
                'weight' => '3.00',
                'width' => '3.00',
                'length' => '3.00',
                'height' => '3.00',
                'insure_it' => 'Yes',
                'insure_amount' => '0.00',
                'is_fragile' => 'Yes',
            ),
            6 => 
            array (
                'id' => 7,
                'loadoard_id' => 7,
                'deliver_from' => 'office',
                'to_office_id' => 1,
                'sender_name' => 'NULL',
                'sender_phone' => 'NULL',
                'sender_zipcode' => 'NULL',
                'sender_city' => 'NULL',
                'sender_street' => 'NULL',
                'sender_number' => 'NULL',
                'sender_appartment' => 'NULL',
                'deliver_to' => 'address',
                'from_office_id' => 1,
                'receiver_name' => 'NULL',
                'receiver_phone' => 'NULL',
                'receiver_zipcode' => 'NULL',
                'receiver_city' => 'NULL',
                'receiver_street' => 'NULL',
                'receiver_number' => 'NULL',
                'receiver_appartment' => 'NULL',
                'is_document' => 'Yes',
                'description' => NULL,
                'weight' => '4.00',
                'width' => '4.00',
                'length' => '4.00',
                'height' => '4.00',
                'insure_it' => NULL,
                'insure_amount' => '0.00',
                'is_fragile' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'loadoard_id' => 8,
                'deliver_from' => 'address',
                'to_office_id' => 1,
                'sender_name' => 'NULL',
                'sender_phone' => 'NULL',
                'sender_zipcode' => 'NULL',
                'sender_city' => 'NULL',
                'sender_street' => 'NULL',
                'sender_number' => 'NULL',
                'sender_appartment' => 'NULL',
                'deliver_to' => 'office',
                'from_office_id' => 1,
                'receiver_name' => 'NULL',
                'receiver_phone' => 'NULL',
                'receiver_zipcode' => 'NULL',
                'receiver_city' => 'NULL',
                'receiver_street' => 'NULL',
                'receiver_number' => 'NULL',
                'receiver_appartment' => 'NULL',
                'is_document' => 'No',
                'description' => NULL,
                'weight' => '2.00',
                'width' => '2.00',
                'length' => '22.00',
                'height' => '3.00',
                'insure_it' => 'Yes',
                'insure_amount' => '0.00',
                'is_fragile' => 'Yes',
            ),
            8 => 
            array (
                'id' => 9,
                'loadoard_id' => 9,
                'deliver_from' => 'address',
                'to_office_id' => 1,
                'sender_name' => 'NULL',
                'sender_phone' => 'NULL',
                'sender_zipcode' => 'NULL',
                'sender_city' => 'NULL',
                'sender_street' => 'NULL',
                'sender_number' => 'NULL',
                'sender_appartment' => 'NULL',
                'deliver_to' => 'address',
                'from_office_id' => 1,
                'receiver_name' => 'NULL',
                'receiver_phone' => 'NULL',
                'receiver_zipcode' => 'NULL',
                'receiver_city' => 'NULL',
                'receiver_street' => 'NULL',
                'receiver_number' => 'NULL',
                'receiver_appartment' => 'NULL',
                'is_document' => 'No',
                'description' => NULL,
                'weight' => '4.00',
                'width' => '4.00',
                'length' => '5.00',
                'height' => '5.00',
                'insure_it' => 'No',
                'insure_amount' => '0.00',
                'is_fragile' => 'Yes',
            ),
            9 => 
            array (
                'id' => 10,
                'loadoard_id' => 10,
                'deliver_from' => 'address',
                'to_office_id' => 1,
                'sender_name' => 'victor',
                'sender_phone' => '081327156',
                'sender_zipcode' => '2156',
                'sender_city' => 'lagos',
                'sender_street' => 'alaba',
                'sender_number' => '12',
                'sender_appartment' => 'phase 3',
                'deliver_to' => 'address',
                'from_office_id' => 1,
                'receiver_name' => 'kike',
                'receiver_phone' => '08523266+6',
                'receiver_zipcode' => '22323',
                'receiver_city' => 'jaga',
                'receiver_street' => 'street name',
                'receiver_number' => '23',
                'receiver_appartment' => 'NULL',
                'is_document' => 'No',
                'description' => 'package Description',
                'weight' => '52.00',
                'width' => '232.00',
                'length' => '552.00',
                'height' => '41.00',
                'insure_it' => 'Yes',
                'insure_amount' => '1000.00',
                'is_fragile' => 'Yes',
            ),
            10 => 
            array (
                'id' => 11,
                'loadoard_id' => 11,
                'deliver_from' => 'address',
                'to_office_id' => 1,
                'sender_name' => 'NULL',
                'sender_phone' => 'NULL',
                'sender_zipcode' => 'NULL',
                'sender_city' => 'NULL',
                'sender_street' => 'NULL',
                'sender_number' => 'NULL',
                'sender_appartment' => 'NULL',
                'deliver_to' => 'address',
                'from_office_id' => 1,
                'receiver_name' => 'NULL',
                'receiver_phone' => 'NULL',
                'receiver_zipcode' => 'NULL',
                'receiver_city' => 'NULL',
                'receiver_street' => 'NULL',
                'receiver_number' => 'NULL',
                'receiver_appartment' => 'NULL',
                'is_document' => 'No',
                'description' => 'ewww',
                'weight' => '222.90',
                'width' => '232.00',
                'length' => '232.00',
                'height' => '232.00',
                'insure_it' => 'Yes',
                'insure_amount' => '0.00',
                'is_fragile' => 'No',
            ),
            11 => 
            array (
                'id' => 12,
                'loadoard_id' => 12,
                'deliver_from' => NULL,
                'to_office_id' => 1,
                'sender_name' => 'lawal',
                'sender_phone' => '08132712715',
                'sender_zipcode' => 'lagos',
                'sender_city' => 'ikeja',
                'sender_street' => 'adeola',
                'sender_number' => '2',
                'sender_appartment' => 'null',
                'deliver_to' => 'address',
                'from_office_id' => 1,
                'receiver_name' => 'Daniel',
                'receiver_phone' => '084625562263',
                'receiver_zipcode' => 'Abia',
                'receiver_city' => 'taio',
                'receiver_street' => 'raru',
                'receiver_number' => '45',
                'receiver_appartment' => 'NULL',
                'is_document' => 'No',
                'description' => 'Package Description',
                'weight' => '12.00',
                'width' => '23.00',
                'length' => '12.00',
                'height' => '11.00',
                'insure_it' => 'No',
                'insure_amount' => '1000.00',
                'is_fragile' => 'Yes',
            ),
        ));
        
        
    }
}