<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('users')->delete();

        \DB::table('users')->insert(array (
            0 =>
            array (
                'id' => 1,
                'full_name' => 'super admin',
                'email' => 'admin@monodome.co',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$8LBMPVdIM97Sxh2q2diibeo/zvg40EWUe929AtVjuHZSi.NWvO1om',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => NULL,
                'imageUrl' => NULL,
                'user_type' => 'super_admin',
                'role' => NULL,
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:22:23',
                'updated_at' => '2023-10-30 13:22:23',
            ),
            1 =>
            array (
                'id' => 2,
                'full_name' => 'admin',
                'email' => 'admin@example.com',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$rmBJp3285EEP9N9gDVorN.oKJF/0gEEm25pCkrzRBWs3auEFT2Hk6',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => NULL,
                'imageUrl' => NULL,
                'user_type' => 'admin',
                'role' => NULL,
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:22:23',
                'updated_at' => '2023-10-30 13:22:23',
            ),
            2 =>
            array (
                'id' => 3,
                'full_name' => 'Customer',
                'email' => 'customer@gmail.com',
                'phone_number' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$ls19QB7MfG39OL0BmrkLVuzgN1VbAyQ/UlkzIfGbWBCyu/5cFIfTG',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => NULL,
                'imageUrl' => NULL,
                'user_type' => 'customer',
                'role' => NULL,
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:22:23',
                'updated_at' => '2023-10-30 13:22:23',
            ),
            3 =>
            array (
                'id' => 4,
                'full_name' => 'Cindy Mosciski',
                'email' => 'Hoyt.Zieme58@hotmail.com',
                'phone_number' => '07063367845',
                'email_verified_at' => NULL,
                'password' => '$2y$10$SPwTVx/7m6Kv0uwqN0KNCuPIArM7ng/wFc609MSClv9E5TpaI8Fs2',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => NULL,
                'imageUrl' => NULL,
                'user_type' => 'driver',
                'role' => NULL,
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:25:02',
                'updated_at' => '2023-10-30 13:25:02',
            ),
            4 =>
            array (
                'id' => 5,
                'full_name' => 'Linda Pagac',
                'email' => 'William_Armstrong61@hotmail.com',
                'phone_number' => '07043367845',
                'email_verified_at' => NULL,
                'password' => '$2y$10$stIrDcnS2ErS6wOTqURRMOJ0f4bc9/b8/u0HzhzVp8fssT4c772Eq',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => NULL,
                'imageUrl' => NULL,
                'user_type' => 'driver',
                'role' => NULL,
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:25:22',
                'updated_at' => '2023-10-30 13:25:22',
            ),
            5 =>
            array (
                'id' => 6,
                'full_name' => 'Ms. Meredith Beer',
                'email' => 'Anthony.Ryan40@hotmail.com',
                'phone_number' => '07043367846',
                'email_verified_at' => NULL,
                'password' => '$2y$10$GlFDMGm51RUP0wqITOBymeXOe/X2lMnvncZcg3LcntMNFC6n0yELm',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => NULL,
                'imageUrl' => NULL,
                'user_type' => 'driver',
                'role' => NULL,
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:25:29',
                'updated_at' => '2023-10-30 13:25:29',
            ),
            6 =>
            array (
                'id' => 7,
                'full_name' => 'Claudia Wisoky',
                'email' => 'Helene.Wintheiser30@gmail.com',
                'phone_number' => '07043367346',
                'email_verified_at' => NULL,
                'password' => '$2y$10$jOpe.nJK0WYKK2wQphtDA.icrwjsdf0m9rCManIXstBz/A39NXLvG',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => NULL,
                'imageUrl' => NULL,
                'user_type' => 'driver',
                'role' => NULL,
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:25:42',
                'updated_at' => '2023-10-30 13:25:42',
            ),
            7 =>
            array (
                'id' => 8,
                'full_name' => 'Edna Rau II',
                'email' => 'Rusty66@gmail.com',
                'phone_number' => '07043167346',
                'email_verified_at' => NULL,
                'password' => '$2y$10$WEr5rqZAUkSEY6zE41H/rusPAIHNdcOuFwGWHsM.JDJxrcG5mVT2e',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => NULL,
                'imageUrl' => NULL,
                'user_type' => 'driver',
                'role' => NULL,
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:25:59',
                'updated_at' => '2023-10-30 13:25:59',
            ),
            8 =>
            array (
                'id' => 9,
                'full_name' => 'Felipe White PhD',
                'email' => 'Alisa.Veum71@hotmail.com',
                'phone_number' => '+2347064641016',
                'email_verified_at' => NULL,
                'password' => '$2y$10$JwHxOudHRpdZy89L0dMAjeD8FMiY3AykheaSbp1r6jta/lHwiDxVC',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => NULL,
                'imageUrl' => NULL,
                'user_type' => 'broker',
                'role' => NULL,
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:28:03',
                'updated_at' => '2023-10-30 13:28:03',
            ),
            9 =>
            array (
                'id' => 10,
                'full_name' => 'Christian Moen',
                'email' => 'Elisa.Swift@yahoo.com',
                'phone_number' => '+2347064341016',
                'email_verified_at' => NULL,
                'password' => '$2y$10$mWssotiFVYQ6SulCyQzLiezvyGFUXb5uAiDK8qeOzpjywDtX/EjDK',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => NULL,
                'imageUrl' => NULL,
                'user_type' => 'broker',
                'role' => NULL,
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:28:13',
                'updated_at' => '2023-10-30 13:28:13',
            ),
            10 =>
            array (
                'id' => 11,
                'full_name' => 'Jerry Ward',
                'email' => 'Viva42@hotmail.com',
                'phone_number' => '0709464409',
                'email_verified_at' => NULL,
                'password' => '$2y$10$dSCKv1m7tabXFbh9cquAS.YHcvdbz18r9GU.X6kij3y.p0Baltowi',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => '5',
                'imageUrl' => NULL,
                'user_type' => 'shipping_company',
                'role' => 'super_admin',
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:29:03',
                'updated_at' => '2023-10-30 13:29:07',
            ),
            11 =>
            array (
                'id' => 12,
                'full_name' => 'Mrs. Johnny Volkman',
                'email' => 'Jerrold93@gmail.com',
                'phone_number' => '0709464407',
                'email_verified_at' => NULL,
                'password' => '$2y$10$/L8wpzUJVC3CVnRC/vGUCO9NY9KQPjG.MoqIdv0tFHpDqRApBZJk6',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => '5',
                'imageUrl' => NULL,
                'user_type' => 'shipping_company',
                'role' => 'super_admin',
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:29:18',
                'updated_at' => '2023-10-30 13:29:21',
            ),
            12 =>
            array (
                'id' => 13,
                'full_name' => 'Michael Smitham',
                'email' => 'Jovan44@yahoo.com',
                'phone_number' => '07079464407',
                'email_verified_at' => NULL,
                'password' => '$2y$10$gQuGnyFvPpbN2/kpumJZbeutcpR9TAH0zsLFuTduRllmGlGpIHwAu',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => '5',
                'imageUrl' => NULL,
                'user_type' => 'shipping_company',
                'role' => 'super_admin',
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:29:41',
                'updated_at' => '2023-10-30 13:29:45',
            ),
            13 =>
            array (
                'id' => 14,
                'full_name' => 'Cecelia Goldner',
                'email' => 'lapsakelti@gufum.com',
                'phone_number' => '07635252726',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ti9JQ60YwkILpwB/za4OU.Xqtm6hh1TAHN58cGBxzDLwBd1BT9Cc2',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => '10',
                'imageUrl' => 'uploads/company/company_images/1698672655v2qTkyaPjU.png',
                'user_type' => 'company_transport',
                'role' => 'Company Transport',
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:30:55',
                'updated_at' => '2023-10-30 13:30:59',
            ),
            14 =>
            array (
                'id' => 17,
                'full_name' => 'Willie Veum',
                'email' => 'Tyler46@hotmail.com',
                'phone_number' => '076352522726',
                'email_verified_at' => NULL,
                'password' => '$2y$10$etfFWPvBIrh8Z0kHRdubKOI39MibCNjWPh7vucuCO3R0oSYNx9Z1i',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => '10',
                'imageUrl' => 'uploads/company/company_images/1698672743oFyPgQbdTp.png',
                'user_type' => 'company_transport',
                'role' => 'Company Transport',
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:32:23',
                'updated_at' => '2023-10-30 13:32:29',
            ),
            15 =>
            array (
                'id' => 18,
                'full_name' => 'Noel Blanda',
                'email' => 'Addison_Schumm@yahoo.com',
                'phone_number' => '076352522725',
                'email_verified_at' => NULL,
                'password' => '$2y$10$QMBn3EYUHASjxY3MdBYlBOk6ZuOiCkZFuqDkIDsGmemniZlFeeSmC',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => '10',
                'imageUrl' => 'uploads/company/company_images/1698672776sREHvqZBdZ.png',
                'user_type' => 'company_transport',
                'role' => 'Company Transport',
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:32:56',
                'updated_at' => '2023-10-30 13:32:59',
            ),
            16 =>
            array (
                'id' => 19,
                'full_name' => 'Guy Oberbrunner',
                'email' => 'Stephon.Hoppe56@yahoo.com',
                'phone_number' => '076352511725',
                'email_verified_at' => NULL,
                'password' => '$2y$10$zzPlX5DifASnEV117EPeRec6/f8UOArr6jra182LmHib9nBmTrFxW',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => '10',
                'imageUrl' => 'uploads/company/company_images/1698672859YfbPHCjyAl.png',
                'user_type' => 'company_transport',
                'role' => 'Company Transport',
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:34:19',
                'updated_at' => '2023-10-30 13:34:24',
            ),
            17 =>
            array (
                'id' => 20,
                'full_name' => 'Eula Barton',
                'email' => 'Rasheed69@hotmail.com',
                'phone_number' => '07011611144',
                'email_verified_at' => NULL,
                'password' => '$2y$10$eY2s6Gk1vNKb443Xsl7qf.dQanjxEKoGg2b0h4XR1s9ghJmxycsw2',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => NULL,
                'imageUrl' => NULL,
                'user_type' => 'agent',
                'role' => NULL,
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:36:23',
                'updated_at' => '2023-10-30 13:36:23',
            ),
            18 =>
            array (
                'id' => 21,
                'full_name' => 'Verna Runolfsson',
                'email' => 'riknespe@gufum.com',
                'phone_number' => '070642364315',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Y6AvH7/gRd9Eahs8Ux4cIOlOFKPEYI5IbvCZDN5ism6Pj/Fh5H/cu',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => NULL,
                'imageUrl' => NULL,
                'user_type' => 'driver_manager',
                'role' => NULL,
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:37:57',
                'updated_at' => '2023-10-30 13:37:57',
            ),
            19 =>
            array (
                'id' => 22,
                'full_name' => 'Truck',
                'email' => 'Natasha.Kozey63@yahoo.com',
                'phone_number' => '070779873623',
                'email_verified_at' => NULL,
                'password' => '$2y$10$FpTHCG5iQVxhI46cFocYMOBlfQxVHMOYZdSL5QDlqZOEe06mIaZC.',
                'provider_id' => NULL,
                'provider' => NULL,
                'address' => NULL,
                'user_created_by' => NULL,
                'role_id' => NULL,
                'imageUrl' => NULL,
                'user_type' => 'truck',
                'role' => NULL,
                'location' => NULL,
                'user_agent' => NULL,
                'status' => 'Pending',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2023-10-30 13:39:26',
                'updated_at' => '2023-10-30 13:39:26',
            ),
        ));


    }
}
